### ISSUE TITLE
Implement method for calculating the bonus

### ISSUE THREAD

**Issue by JovanovicMarija** [devjos/ase_project#11]

**Comment by devjos** [comment]
some hard coded value for now

**Comment by JovanovicMarija** [comment]
I would not hard code it. Why not return something like:
return (numberOfClassessAttended == totalNumberOfClasses) && didStudentPresent
Maybe give student 2 joker classes he/she can skip:
return (numberOfClassessAttended+2 >= totalNumberOfClasses) && didStudentPresent
For now, yes, it will always return false, but as we develop our system, we can test it, and not re-write it.
